config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/help", to: "pages#help"

  get '/courses/search', to: 'courses#live_search'
  get '/courses/my_courses', to: 'courses#my_courses'

  resources :courses do
    resources :lessons, only: %i[index new create show] do
      resources :topics, only: %i[create show]
    end
  end
  resources :courses do
    post '/reviews', to: 'reviews#create'
    post '/subscribe', to: 'course_subscriptions#create'
    delete '/unsubscribe', to: 'course_subscriptions#destroy'
  end

  # Handling posts
    post '/posts', to: 'posts#create'

    get "/statistics/:id", to: "pages#statistics" , as: 'statistics'

  namespace :api do
    post '/chat', to: 'ai#answer'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if !current_page?(root_path) %>
  <footer class="text-center text-lg-start footer-mentor text-white mt-5">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Connect to @mentorme on social networks:</span>
      </div>
      <!-- Left -->
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>mentor.me
            </h6>
            <p>
              We are an open source, peer 2 peer learning platform for developers. We believe that everyone has something to teach and something to learn. We are a community of developers who are passionate about learning and teaching together.
            </p>
          </div>
          <!-- Grid column -->
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Categories
            </h6>
            <% Category.all.last(5).each do |category| %>
              <p>
                <%= link_to category.category, courses_path(category: category.category), class: "text-reset" %>
              </p>
            <% end %>
          </div>
          <!-- Grid column -->
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <%= link_to "Home", root_path, class: "text-reset" %>
            </p>
            <p>
              <%= link_to "Courses", courses_path, class: "text-reset" %>
            </p>
            <p>
              <%= link_to "Become a mentor", new_course_path, class: "text-reset" %>
            </p>
            <p>
              <% if !user_signed_in? %>
                <%= link_to "Login", new_user_session_path, class: "text-reset" %>
              <% end %>
            </div>
            <!-- Grid column -->
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                  hr@mentorme.learn
              </p>
              <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
              <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
      <!-- Copyright -->
      <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2023 Copyright:
        <a class="text-reset fw-bold" href="https://mentorme.learn">mentorme.learn</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  <% end %>

app/views/shared/_minibanner.erb
<div class="mini-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= background_img_mini_bar %>);">
  <div class="container">
    <h1> <%= title %> </h1>
    <p> <%= subtitle %> </p>
      <h2 class=""> <%= button_action %> </h2>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if !current_page?(root_path) %>
  <div class="navbar navbar-expand-sm navbar-lewagon ">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand text-white" do %>
      <img src="https://res.cloudinary.com/devnbwk8s/image/upload/v1686823995/logo_lukpdv.png">
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "navbar-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Browse Courses", courses_path, class: "navbar-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Courses", courses_my_courses_path, class: "navbar-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Become a mentor", new_course_path, data: { turbo: 'false' },  class: "navbar-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "How does it work?", help_path,  class: "navbar-link" %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="navbar-link"  id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Profile
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Public Profile", statistics_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>