config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/help", to: "pages#help"

  get '/courses/search', to: 'courses#live_search'
  get '/courses/my_courses', to: 'courses#my_courses'

  resources :courses do
    resources :lessons, only: %i[index new create show] do
      resources :topics, only: %i[create show]
    end
  end
  resources :courses do
    post '/reviews', to: 'reviews#create'
    post '/subscribe', to: 'course_subscriptions#create'
    delete '/unsubscribe', to: 'course_subscriptions#destroy'
  end

  # Handling posts
    post '/posts', to: 'posts#create'

    get "/statistics/:id", to: "pages#statistics" , as: 'statistics'

  namespace :api do
    post '/chat', to: 'ai#answer'
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :user_lesson_views, dependent: :destroy
  has_one_attached :video
  has_many :topics, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true
  validates :video, presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show edit update destroy]
  before_action :set_course, only: %i[new create]

  def index
    @lessons = Lesson.all
    @lessons = policy_scope(Lesson)
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.course = @course
    authorize @lesson
    if @lesson.save
      redirect_to course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @lesson = Lesson.new
    @course = Course.find(params[:course_id])
    @lesson.course = @course
    authorize @lesson
  end

  def show
    authorize @lesson
    if !subscribed?
      flash['alert'] = "You need to join the course to view it's contents"
      redirect_to course_path(@lesson.course)
    else
      @user_lesson_view = UserLessonView.new
      @user_lesson_view.user = current_user
      @user_lesson_view.lesson = @lesson
      @user_lesson_view.save
      @topic = Topic.new
      @topics = Topic.where(lesson: @lesson).order("id DESC")
    end

  end

  def edit
    authorize @lesson
  end

  def destroy
    @lesson.destroy
    redirect_to lesson_path, status: :see_other
    authorize @lesson
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :description, :video, :course_id, :post_content)
  end

  def subscribed?
     current_user == @lesson.course.user || CourseSubscription.user_subscribed?(current_user, @lesson.course)
  end
end

app/views/lessons/_aichat.html.erb
<div class="chat-wrap">
  <div class="chat" data-aichat-target="messages">
    <div class="chat-message"> This is LearnyBravo. You can ask me any question and I'll try to guide you through your learning process! </div>
  </div>
  <form data-action="submit->aichat#start">
    <div class="input-group mb-3 border border-dark border-1">
      <input type="text" data-aichat-target="prompt" class="form-control" placeholder="I need help with" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-info" type="submit"><i class="fa-solid fa-paper-plane"></i></button>
      </div>
    </div>
  </form>
</div>

app/views/lessons/_form.html.erb
<h2>Lessons</h2>

  <div class="form-inputs">

     <%= f.input :name,
                input_html: { autocomplete: "Name" }%>
      <%= f.input :description,
                input_html: { autocomplete: "Description" }%>
    <%= f.input :video_url,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "video_url" }%>
      <%= f.input :post_content,
                input_html: { autocomplete: "post_content" }%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create new lesson" %>
  </div>

app/views/lessons/index.html.erb
<h1>@View</h1>

app/views/lessons/new.html.erb
<div class="container my-5">
  <h3 class="text-main"><i class="fa-solid fa-greater-than"></i> Add new lesson to <%= @course.name %></h3>
  <p><span class="text-info">Important: </span> Here you can update your course and add lessons to it. It is very important that you add an accurate description,
   because our AI assistant uses it as context, along with the course description, to give accurate answers. Also, having an accurate description to both your courses
    and lectures helps your ranking in search! </p>

<%= simple_form_for [@course, @lesson] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :video, as: :file %>
  <%= f.input :post_content, as: :text, input_html: { class: "tinymce" } %>
  <%= tinymce %>
  <%= f.submit class: "btn btn-info" %>
<% end %>
</div>

app/views/lessons/show.html.erb
<% title = @lesson.name %>
<% subtitle = @lesson.description %>
<% button_action = "" %>
<% background_img_mini_bar = "https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" %>
<%= render "shared/minibanner", title: title, subtitle: subtitle, button_action: button_action, background_img_mini_bar: background_img_mini_bar %>

<div class="container" data-controller="aichat">
  <input type="hidden" data-aichat-target="courseTitle" value="<%= @lesson.course.name %>">
  <input type="hidden" data-aichat-target="courseDesc" value="<%= @lesson.course.description %>">
  <input type="hidden" data-aichat-target="lessonTitle" value="<%= @lesson.name %>">
  <input type="hidden" data-aichat-target="lessonDesc" value="<%= @lesson.description %>">

  <ul class="nav nav-tabs my-3">
    <li class="nav-item">
      <%= link_to "Video", "#videoTab", class: "nav-link active text-main", "data-bs-toggle": "tab" %>
    </li>
    <li class="nav-item ">
      <%= link_to "Community Topics", "#topicsTab", class: "nav-link  text-main", "data-bs-toggle": "tab" %>
    </li>
    <li class="nav-item ">
      <%= link_to "Text Lesson", "#textLessonTab", class: "nav-link  text-main", "data-bs-toggle": "tab" %>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade show active" id="videoTab">
      <div class="row">
        <div class="col-8">
          <div data-controller="plyr">
            <%= cl_video_tag(@lesson.video.key,
                            loop: true, controls: true,
                            id: "course-player",
                            fallback_content: "Your browser does not support HTML5 video tags.",
                            transformation: [{ crop: "fill" }]
                            ) %>
          </div>
        </div>
        <div class="col-4">
          <%= render "lessons/aichat" %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="topicsTab">
    <h3>Start a topic on the lesson</h3>
      <%= simple_form_for [@lesson.course, @lesson, @topic] do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.text_field :timestamp, value: 0, id: "timestamp", type: "hidden" %>
        <%= f.submit class: "btn btn-info" %>
      <% end %>
      <hr>
      <h6>Community Forums</h6>
      <% @topics.each do |topic| %>
        <%= link_to course_lesson_topic_path(@lesson.course, @lesson, topic), class: "text-decoration-none" do %>
          <div class="card bg-info-subtle my-3 border-0 border-5 border-start border-primary-subtle">
            <div class="card-body">
              <h5><%= topic.title %> <span class="badge bg-dark"><%= Time.at(topic.timestamp).utc.strftime("%M:%S") %></span></h5>
              <small class="text-muted">By <%= topic.user.first_name %></small>
              <p><%= topic.content %></p>
              <i class="fa-regular fa-comment-dots"></i> <%= pluralize(topic.posts.count, "reply") %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="textLessonTab">
      <div class="row">
      <% if !@lesson.post_content.empty? %>
        <div class="col-sm-6">
          <h4 class="text-main my-3"><i class="fa-solid fa-tablet-screen-button"></i> <%= @lesson.name %></h4>
        </div>
        <div class="col-sm-6 text-end">
          <% minutes = @lesson.post_content.split(" ").count / 200 + 1%>
          <h6 class="text-main my-3"> Posted by <%= @lesson.course.user.nickname %><br><%= pluralize(minutes, "minute") %> read </h6>
          </div>
          <div class="col-12">
          <p class="text-muted mt-3">
            <%= raw(@lesson.post_content) %>
          </p>
          </div>
        </div>
        <% else %>
        <div class="col-sm-6">
          <h4 class="text-main my-3"><i class="fa-solid fa-wrench"></i> Sorry, this lesson doesn't have a text version yet.</h4>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("turbo:load", function () {
    const navLinks = document.querySelectorAll(".nav-link[data-bs-toggle='tab']");
    const tabContents = document.querySelectorAll(".tab-pane");
    const videoPlayer = document.getElementById("course-player");
    const timestampInput = document.getElementById("timestamp");

    navLinks.forEach(function (link) {
      link.addEventListener("click", function (e) {
        e.preventDefault();
        const target = this.getAttribute("href");
        navLinks.forEach(function (navLink) {
          navLink.classList.remove("active");
        });
        tabContents.forEach(function (tabContent) {
          tabContent.classList.remove("show", "active");
        });
        this.classList.add("active");
        document.querySelector(target)?.classList.add("show", "active");
      });
    });

    videoPlayer.addEventListener("timeupdate", function () {
      const currentTime = Math.floor(videoPlayer.currentTime);
      timestampInput.value = currentTime;
    });
  });
</script>


<script>
  document.addEventListener("turbo:load", function () {
    const navLinks = document.querySelectorAll(".nav-link[data-bs-toggle='tab']");
    const tabContents = document.querySelectorAll(".tab-pane");

    navLinks.forEach(function (link) {
      link.addEventListener("click", function (e) {
        e.preventDefault();
        const target = this.getAttribute("href");
        navLinks.forEach(function (navLink) {
          navLink.classList.remove("active");
        });
        tabContents.forEach(function (tabContent) {
          tabContent.classList.remove("show", "active");
        });
        this.classList.add("active");
        document.querySelector(target)?.classList.add("show", "active");
      });
    });
  });
</script>