config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/help", to: "pages#help"

  get '/courses/search', to: 'courses#live_search'
  get '/courses/my_courses', to: 'courses#my_courses'

  resources :courses do
    resources :lessons, only: %i[index new create show] do
      resources :topics, only: %i[create show]
    end
  end
  resources :courses do
    post '/reviews', to: 'reviews#create'
    post '/subscribe', to: 'course_subscriptions#create'
    delete '/unsubscribe', to: 'course_subscriptions#destroy'
  end

  # Handling posts
    post '/posts', to: 'posts#create'

    get "/statistics/:id", to: "pages#statistics" , as: 'statistics'

  namespace :api do
    post '/chat', to: 'ai#answer'
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    if params[:category].present?
      category = Category.where(category: params[:category])
    end
    if params[:query].present?
      if params[:category].present?
        @courses = Course.search_by_name_and_description(params[:query]).where(category: category)
      else
        @courses = Course.search_by_name_and_description(params[:query])
      end
    else
      if params[:category].present?
        @courses = Course.where(category: category)
      else
        @courses = Course.all
      end
    end
    policy_scope(Course)
  end

  def my_courses
    @courses = current_user.courses
    authorize @courses
  end

  def live_search
    query = params[:query]

    if query.present?
      courses = Course.search_by_name_and_description(query)
    else
      courses = Course.all
    end

    authorize courses

    render json: courses
  end

  def show
    authorize @course
    if user_signed_in?
      @course_subscriptions = current_user.course_subscriptions
    else
      @course_subscriptions = false
    end
    @highest_viewed = UserLessonView.where(user: current_user, lesson: @course.lessons).order("id DESC").first
    @lessons = Lesson.where(course: @course)
    @review = Review.new
    @reviews = Review.all.where(course: @course).order("id DESC").first(10)
  end

  def new
    @course = Course.new
    @categories = Category.all
    authorize @course
  end

  def create
    @course = Course.new(course_params.except(:category))
    category = Category.find(params[:course][:category])
    @course.category = category
    @course.user = current_user
    authorize @course
    if @course.save
      redirect_to course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @course
  end

  def update
    authorize @course
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @course
    @course.destroy
    flash[:alert] = "You have successfully deleted a course!"
    redirect_to courses_my_courses_path, status: :see_other
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :poster, :category)
  end
end

app/views/courses/_add_review.html.erb
<% if (current_user != @course.user) %>
  <% if !Review.user_reviewed?(current_user, @course) && CourseSubscription.user_subscribed?(current_user, @course)%>
  <hr>
<h6 class="text-end">Create a new Review</h6>
  <%= simple_form_for [@course, @review] do |f| %>
  <%= f.label :Stars %> <br>
  <div class= "rating">
    <%= f.collection_radio_buttons :stars, [[5], [4], [3], [2], [1]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b| %>
      <%= b.radio_button %>
      <%=  b.label(class: "text-white remove") %>
    <% end %> <br>
  </div>
  <br>
  <%= f.input :description %>
<hr>
  <%= f.submit class: "btn btn-info" %>
<% end %>


    <% end %>
<% end %>

app/views/courses/_display_review.html.erb
<h5 class="text-main mt-5 text-end"><i class="fa-solid fa-star"></i> Latest reviews</h5>
<hr>
  <% if @reviews.count.zero? %>
    <h5>No reviews yet</h5>
  <% end %>
<% @reviews.each do |review| %>
  <div class="card border-0 mt-1">
    <div class="card-body border-start border-primary border-3">
      <p class="fs-5"><%= review.description %></p>
      <% review.stars.times do %>
        <span class="fa-solid fa-star text-warning"></span>
      <% end  %> <br>
      <small>
      <%= review.user.nickname %>
      <%= review.created_at.strftime("%d/%m/%Y") %>
      </small>
    </div>
  </div>
<% end %>

app/views/courses/_subscribe.html.erb
<div class="float-end">
<% if (current_user != @course.user) %>
  <% if CourseSubscription.user_subscribed?(current_user, @course) %>
    <%= link_to "Unsubscribe", course_unsubscribe_path(@course),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-lg btn-info" %>
  <% else %>
    <%= button_to course_subscribe_path(@course), class: "btn btn-info btn-lg" do %>
      <i class="fa-solid fa-square-plus"></i> Join Course
    <% end %>
  <% end %>
<% end %>
</div>

app/views/courses/edit.html.erb
<div class="container my-5">
  <h3 class="text-main">Edit Course Details</h3>
  <p>Please pay attention. Altering your course name and description will also alter the way it can be found by search! </p>
  <%= simple_form_for(@course) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text, input_html: { class: "tinymce" } %>
    <%= tinymce %>
    <%= f.input :poster, as: :file %>
    <%= f.button :submit, "Update Course", class: "btn btn-info" %>
  <% end %>
</div>

app/views/courses/index.html.erb
<% if params[:query].present? %>
  <% title = "Searching #{params[:query].capitalize} Courses" %>
<% else %>
  <% if params[:category].present? %>
    <% title = "Browsing #{params[:category].capitalize} Courses" %>
  <% else %>
    <% title = "Browsing all courses" %>
  <% end %>
<% end %>
<% subtitle = "We have a library of  #{pluralize(@courses.count, 'course')}" %>
<% button_action = link_to "Create Course", new_course_path, data: { turbo: 'false' }, class: "btn btn-info"  %>
<% background_img_mini_bar = 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1674&q=80' %>
<%= render "shared/minibanner", title: title, subtitle: subtitle, button_action: button_action, background_img_mini_bar: background_img_mini_bar %>
<div class= "container">
  <div class="row my-4">
    <div class="col-6">
      <%= form_with url: courses_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by course name or description"
        %>
        <%= submit_tag "Search", name: "", class: "btn btn-info" %>
      <% end %>
    </div>
    <div class="col-2 offset-4">
      <div class="dropdown float-end">
        <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-filter"></i> Categories
        </button>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.category, courses_path(category: category.category), class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <main class="grid">
      <% if @courses.count.zero? %>
        <h3 class="text-center">No courses found</h3>
      <% end %>
      <% @courses.each do |course| %>
        <article class= "card-wrap">
          <div class="category-card badge bg-info">
            <i class="fa-solid fa-tags"></i> <%= course.category.category %>
          </div>
          <% if CourseSubscription.user_subscribed?(current_user, course) %>
            <div class="category-card-right badge bg-warning">
              <i class="fa-regular fa-circle-check"></i> subscribed
            </div>
          <% end %>
          <%= cl_image_tag course.poster.key, crop: :fill, class: "img-fluid border-bottom" %>
          <div class="course-content">
            <p class= "text-main d-flex justify-content-between">
              <span>
                <i class="fa-brands text-main fa-youtube"></i> <%= pluralize(course.lessons.count, 'lesson') %>
              </span>
              <span>
                <i class="fa-solid text-warning fa-star"></i> <%= course.calculate_review(course) %>
                <span class= "text-muted small-text">(<%= pluralize(course.reviews.count, "review") %>)</span>
              </span>
            </p>
            <div class="text">
              <h5 class= "mt-2 path"><%= link_to course.name,  course_path(course) ,class: "hide" %></h5>
              <p class="description">
                <%= ActionView::Base.full_sanitizer.sanitize(course.description.first(100)) %></p>
            </div>
            <% if course.user == current_user%>
              <p class="text-main float-start"><i class="fa-solid fa-at"></i> Your Course
              <%= link_to statistics_path(course.user) do %>
              <i class="fa-solid fa-chart-simple"></i>
              <% end %>

              </p>

              <% else %>
            <p class="text-main float-start"><i class="fa-solid fa-at"></i> <%= course.user.nickname %>
              <%= link_to statistics_path(course.user) do %>
              <i class="fa-solid fa-chart-simple"></i>
              <% end %>
            </p>
            <% end %>
            <%= link_to "View Details", course_path(course), class: "btn btn-sm btn-info float-end mb-3" %>
          </div>
        </article>
      <% end %>
    </main>
  </div>
</div>

app/views/courses/my_courses.html.erb
<% title = "Courses Manager Dashboard" %>
<% subtitle = "So far you have created  #{pluralize(@courses.count, 'course')}" %>
<% button_action = link_to "Create Course", new_course_path, data: { turbo: 'false' }, class: "btn btn-info"  %>
<% background_img_mini_bar = 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1674&q=80' %>
<%= render "shared/minibanner", title: title, subtitle: subtitle, button_action: button_action, background_img_mini_bar: background_img_mini_bar %>
<div class= "container">
  <div class="row">
  <% if @courses.count.zero? %>
        <h3 class="text-center my-5">You have not added any courses to our platform yet. You can start do to so at any moment!</h3>
      <% end %>
    <main class="grid my-4">

      <% @courses.each do |course| %>
        <article class= "card-wrap">
          <div class="category-card badge bg-info">
            <i class="fa-solid fa-tags"></i> <%= course.category.category %>
          </div>
          <% if CourseSubscription.user_subscribed?(current_user, course) %>
            <div class="category-card-right badge bg-warning">
              <i class="fa-regular fa-circle-check"></i> subscribed
            </div>
          <% end %>
          <%= cl_image_tag course.poster.key, crop: :fill, class: "img-fluid border-bottom" %>
          <div class="course-content">
            <p class= "text-main d-flex justify-content-between">
              <span>
                <i class="fa-brands text-main fa-youtube"></i> <%= pluralize(course.lessons.count, 'lesson') %>
              </span>
              <span>
                <i class="fa-solid text-warning fa-star"></i> <%= course.calculate_review(course) %>
                <span class= "text-muted small-text">(<%= pluralize(course.reviews.count, "review") %>)</span>
              </span>
            </p>
            <div class="text">
              <h5 class= "mt-2 path"><%= link_to course.name,  course_path(course) ,class: "hide" %></h5>
              <p class="description mb-5">
                <%= ActionView::Base.full_sanitizer.sanitize(course.description.first(100)) %></p>
            </div>
            <%= link_to  new_course_lesson_path(course), data: { turbo: 'false' }, class: "btn btn-dark text-white mb-3" do %>
              <i class="fa-solid fa-circle-plus"></i>
            <% end %>
            <%= link_to  course_path(course), class: "btn btn-danger text-white float-end",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure? Deleting this course will remove all lessons and statistics for others!"} do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
            <%= link_to edit_course_path(course), data: { turbo: 'false' }, class: "btn btn-primary mb-3"  do %>
              <i class="fa-regular fa-pen-to-square"></i>
            <% end %>
            <%= link_to course_path(course), class: "btn btn-info mb-3" do %>
              <i class="fa-solid fa-circle-info"></i>
            <% end %>
          </div>
        </article>
      <% end %>
    </main>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container my-5">
  <h2 class="text-main"><i class="fa-solid fa-greater-than"></i> Create a new Course</h2>
  <p> By uploading your course on MentorME, you instantly gain access to a vast community of learners from all corners of the world. Your knowledge and insights can make a significant impact on individuals seeking to enhance their skills and expand their horizons.</p>
  <%= simple_form_for(@course) do |f| %>
    <%= f.input :name, class: "form-control" %>
    <%= f.input :description, as: :text, input_html: { class: "tinymce" } %>
    <%= tinymce %>
    <%= f.input :category, collection: @categories, label_method: :category, value_method: :id, label: "Category", include_blank: false, class: "form-control" %>
    <%= f.input :poster, as: :file, class: "form-control" %>
    <%= f.submit "Create", class: "btn btn-info" %>
  <% end %>
</div>

app/views/courses/show.html.erb
<% title = @course.name %>
<% lessons = "<i class='fa-brands text-white fa-youtube'></i> #{pluralize(@course.lessons.count, 'lesson')}" %>
<% subtitle = "Created by #{@course.user.first_name} #{@course.user.last_name}" %>
<% rating = "<i class='fa-solid text-warning fa-star'></i> #{@course.calculate_review(@course)}" %>
<% button_action = raw("#{lessons} | #{rating}") %>
<% background_img_mini_bar = "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80"%>
<%= render "shared/minibanner", title: title, subtitle: subtitle, button_action: button_action, background_img_mini_bar: background_img_mini_bar %>
<div class="container">
  <% if @course.user == current_user %>
    <hr>
    <h4 class="text-main my-4"> Course Management </h4>
    <%= link_to "Edit Course", edit_course_path(@course), data: { turbo: 'false' }, class: "btn btn-info" %>
    <%= link_to "Add Lesson To Course", new_course_lesson_path(@course), data: { turbo: 'false' }, class: "btn btn-primary" %>
    <%= link_to "Delete", course_path(@course), class: "btn btn-danger text-white float-end",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure? Deleting this course will remove all lessons and statistics for others!"}%>
    <hr>
  <% end %>
  <div class="row mt-3">
    <div class="col-4">
      <%= cl_image_tag @course.poster.key, height: 400, crop: :fill, class: "img-fluid border-solid rounded shadow" %>
      <p class="my-2">
        <div class="badge bg-info">
          <i class="fa-brands text-white fa-youtube"></i>
          <%= @course.category.category %>
        </div>
        <div class="badge bg-info">
          <i class="fa-solid fa-user"></i>
          <%= @course.user.first_name %> <%= @course.user.last_name %>
        </div>
      </p>
    </div>
    <div class="col-6 ps-5">
      <h3 class="mt-2 text-main path"><%= @course.name %></h3>
      <p class="description">
        <%= raw(@course.description) %>
      </p>
    </div>
    <div class="col-2">
      <%= render "courses/subscribe" %>
    </div>
  </div>
  <h5 class=" text-main text-end"><i class="fa-solid fa-book-open-reader"></i> Lessons </h5>
  <hr>
  <% counter = 1 %>
  <% if @lessons.count.zero? %>
    <h5>No lessons added yet!</h5>
  <% end %>
  <% @lessons.each do |lesson| %>
    <% if @highest_viewed.nil? %>
      <div class="row mx-1 border-start border-info border-5 my-1">
      <% else %>
        <% if @highest_viewed.lesson == lesson %>
          <div class="row mx-1 border-start border-success bg-secondary-subtle border-5 my-1">
          <% else %>
            <div class="row mx-1 border-start border-info border-5 my-1">
            <% end %>
          <% end %>
          <div class="col-2">
            <%= cl_image_tag( "#{lesson.video.key}.jpg", :start_offset=>"8.5", :resource_type=>"video", class: "img-fluid") %>
          </div>
          <div class="col-8">
            <h5 class="mt-2 path"><%= link_to "#{counter}. #{lesson.name}", course_lesson_path(@course, lesson) %></h5>
            <% counter = counter+1 %>
            <p class="description text-secondary">
              <%= lesson.description %>
            </p>
          </div>
          <div class="col-2 pt-5">
            <% if UserLessonView.user_viewed?(current_user, lesson) %>
              <% icon_type = "text-main" %>
            <% else %>
              <% icon_type = "text-secondary" %>
            <% end %>
            <%= link_to course_lesson_path(@course, lesson) do %>
              <i class="fa-solid fs-4 fa-play <%= icon_type %>"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <%= render "courses/display_review" %>
      <% if user_signed_in? %>
        <%= render "courses/add_review" %>
      <% end %>
    </div>
  </div>